spring:
  cloud:
    consul:
      config:
        enabled: true
        host: localhost
        port: 8500

    config:
      server:
        git:
          uri: https://github.com/Denis-Liubenkov/Config-server.git
          clone-on-start: true
          default-label: master
  config:
    import: 'optional:consul'

logging:
  level:
    root: INFO
    org.springframework: INFO
server:
  port: 8086
