#server:
#  port: 8080
#spring:
#  application:
#    name: Gateway
#cloud:
#  gateway:
#   routes:
#      - id: books-service
#        uri: http://localhost:8081
#        predicates:
#          - Path=/books/**
#      - id: User-service
#        uri: http://localhost:8082
#        predicates:
#          - Path=/users/**
#      - id: Order-service
#        uri: http://localhost:8083
#        predicates:
#          - Path=/orders/**