#spring:
#  application:
#    name: User-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Users
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
