spring:
  application:
    name: Order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
server:
  port: 8083